import React from "react";
import styles from "@/styles/privacy.module.css";

export default function Privacy() {
    return (
        <section className="max-w-[1920px] mx-auto px-20 py-12">
            <div className={`${styles.c19} ${styles.doc_content}`}>
                <h1 className={styles.c0} id="h.fznxgpf623a1">
                    <span className={styles.c6}>Privacy Policy</span>
                </h1>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span>Our Privacy Policy was last updated on </span>
                    <span className={styles.c14}>[DATE]</span>
                    <span className={styles.c4}>.</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You
                        use the Service and tells You about Your privacy rights and how the law protects You.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span>
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of
                        information in accordance with this Privacy Policy. This Privacy Policy was generated by{" "}
                    </span>
                    <span>
                        <a
                            className={styles.c10}
                            href="https://www.google.com/url?q=https://www.termsfeed.com/privacy-policy-generator/&amp;sa=D&amp;source=editors&amp;ust=1679649725216439&amp;usg=AOvVaw3OjkBaqeZ0fvWN2YKq9LU1"
                        >
                            TermsFeed Privacy Policy Generator
                        </a>
                    </span>
                    <span className={styles.c4}>.</span>
                </p>
                <h2 className={styles.c13} id="h.ha5wlorkiosm">
                    <span className={`${styles.c9}`}>Interpretation and Definitions</span>
                </h2>
                <h3 className={styles.c15} id="h.mnujt3qhvpwc">
                    <span className={styles.c16}>Interpretation</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following
                        definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </span>
                </p>
                <h3 className={styles.c15} id="h.vbc17mbxffk5">
                    <span className={styles.c16}>Definitions</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>For the purposes of this Privacy Policy:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Account</span>
                        <span className={styles.c4}>&quot; means a unique account created for You to access our Service or parts of our Service.</span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Company</span>
                        <span>
                            &quot; (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this
                            Agreement) refers to{" "}
                        </span>
                        <span className={styles.c14}>
                            [COMPANY INFORMATION]
                            <br />
                            <br />
                        </span>
                        <span className={styles.c4}>For the purpose of the GDPR, the Company is the Data Controller.</span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Country</span>
                        <span>&quot; refers to </span>
                        <span className={styles.c14}>[COMPANY_COUNTRY]</span>
                        <span className={styles.c4}>.</span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Cookies</span>
                        <span className={styles.c4}>
                            &quot; are small files that are placed on Your computer, mobile device or any other device by a website, containing the
                            details of Your browsing history on that website among its many uses.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Data Controller</span>
                        <span className={styles.c4}>
                            &quot;, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which
                            alone or jointly with others determines the purposes and means of the processing of Personal Data.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Device</span>
                        <span className={styles.c4}>
                            &quot; means any device that can access the Service such as a computer, a cell phone or a digital tablet.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Personal Data</span>
                        <span className={styles.c4}>
                            &quot; is any information that relates to an identified or identifiable individual.
                            <br />
                            <br />
                            For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number,
                            location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental,
                            economic, cultural or social identity.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Service</span>
                        <span className={styles.c4}>&quot; refers to the Website.</span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Service Provider</span>
                        <span className={styles.c4}>
                            &quot; means any natural or legal person who processes the data on behalf of the Company. It refers to third-party
                            companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the
                            Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the
                            purpose of the GDPR, Service Providers are considered Data Processors.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Usage Data</span>
                        <span className={styles.c4}>
                            &quot; refers to data collected automatically, either generated by the use of the Service or from the Service
                            infrastructure itself (for example, the duration of a page visit).
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>Website</span>
                        <span>&quot; refers to </span>
                        <span className={styles.c14}>[WEBSITE NAME]</span>
                        <span>, accessible from </span>
                        <span className="c4 c14">[WEBSITE_URL]</span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_suxqkadflmqm-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>&quot;</span>
                        <span className={styles.c5}>You</span>
                        <span className={styles.c4}>
                            &quot; means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such
                            individual is accessing or using the Service, as applicable.
                            <br />
                            <br />
                            Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the
                            individual using the Service.
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <h2 className={styles.c13} id="h.mw7chom191o4">
                    <span className={`${styles.c9}`}>Collecting and Using Your Personal Data</span>
                </h2>
                <h3 className={styles.c15} id="h.og67v96jfydf">
                    <span className={styles.c16}>Types of Data Collected</span>
                </h3>
                <h4 className={`${styles.c21}`} id="h.ttu17anr1bya">
                    <span className={`${styles.c24}`}>Personal Data</span>
                </h4>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to
                        contact or identify You. Personally identifiable information may include, but is not limited to:
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_3tycahcz8l3h-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Email address</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>First name and last name</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Phone number</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Address, State, Province, ZIP/Postal code, City</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Usage Data</span>
                    </li>
                </ul>
                <h4 className={`${styles.c21}`} id="h.129dpb7nzamg">
                    <span className={`${styles.c24}`}>Usage Data</span>
                </h4>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>Usage Data is collected automatically when using the Service.</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type,
                        browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages,
                        unique device identifiers and other diagnostic data.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but
                        not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your
                        mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or
                        through a mobile device.
                    </span>
                </p>
                <h4 className={`${styles.c21}`} id="h.5tqx8nu7trxk">
                    <span className={`${styles.c24}`}>Tracking Technologies and Cookies</span>
                </h4>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking
                        technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The
                        technologies We use may include:
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_98hd9pt7g7bq-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Cookies or Browser Cookies.</span>
                        <span className={styles.c4}>
                            &nbsp;A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate
                            when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
                            Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Web Beacons</span>
                        <span className={styles.c4}>
                            . Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to
                            as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited
                            those pages or opened an email and for other related website statistics (for example, recording the popularity of a
                            certain section and verifying system and server integrity).
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or
                        mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>We use both Session and Persistent Cookies for the purposes set out below:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_xhjxrz3psbfv-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>
                            Necessary / Essential Cookies
                            <br />
                            <br />
                        </span>
                        <span className={styles.c4}>
                            Type: Session Cookies
                            <br />
                            <br />
                            Administered by: Us
                            <br />
                            <br />
                            Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use
                            some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies,
                            the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_xhjxrz3psbfv-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>
                            Cookies Policy / Notice Acceptance Cookies
                            <br />
                            <br />
                        </span>
                        <span className={styles.c4}>
                            Type: Persistent Cookies
                            <br />
                            <br />
                            Administered by: Us
                            <br />
                            <br />
                            Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_xhjxrz3psbfv-0">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>
                            Functionality Cookies
                            <br />
                            <br />
                        </span>
                        <span className={styles.c4}>
                            Type: Persistent Cookies
                            <br />
                            <br />
                            Administered by: Us
                            <br />
                            <br />
                            Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login
                            details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to
                            avoid You having to re-enter your preferences every time You use the Website.
                        </span>
                    </li>
                </ul>
                <p className={`${styles.c1} ${styles.c1}`}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_xhjxrz3psbfv-0">
                    <li className="c2 c3 c7 li-bullet-0">
                        <span className={styles.c5}>
                            Tracking and Performance Cookies
                            <br />
                            <br />
                        </span>
                        <span className={styles.c4}>
                            Type: Persistent Cookies
                            <br />
                            <br />
                            Administered by: Third-Parties
                            <br />
                            <br />
                            Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The
                            information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because
                            the information collected is typically linked to a pseudonymous identifier associated with the device you use to access
                            the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our
                            users react to them.
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the
                        Cookies section of our Privacy Policy.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <h2 className={styles.c13} id="h.6s0wtslt7apx">
                    <span className={`${styles.c9}`}>Use of Your Personal Data</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>The Company may use Personal Data for the following purposes:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_x91o64mkwmi3-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>To provide and maintain our Service</span>
                        <span className={styles.c4}>, including to monitor the usage of our Service.</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>To manage Your Account:</span>
                        <span className={styles.c4}>
                            &nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different
                            functionalities of the Service that are available to You as a registered user.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>For the performance of a contract: </span>
                        <span className={styles.c4}>
                            the development, compliance and undertaking of the purchase contract for the products, items or services You have
                            purchased or of any other contract with Us through the Service.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>To contact You:</span>
                        <span className={styles.c4}>
                            &nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a
                            mobile application&#39;s push notifications regarding updates or informative communications related to the
                            functionalities, products or contracted services, including the security updates, when necessary or reasonable for their
                            implementation.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>To provide You with news</span>
                        <span className={styles.c4}>
                            , special offers and general information about other goods, services and events which we offer that are similar to those
                            that you have already purchased or enquired about unless You have opted not to receive such information.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>To manage Your requests: </span>
                        <span className={styles.c4}>To attend and manage Your requests to Us.</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>For business transfers:</span>
                        <span className={styles.c4}>
                            &nbsp;We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization,
                            dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy,
                            liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets
                            transferred.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>For other purposes: </span>
                        <span className={styles.c4}>
                            We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the
                            effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your
                            experience.
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>We may share Your personal information in the following situations:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_372wecfibyc1-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>With Service Providers</span>
                        <span className={styles.c4}>
                            : We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment
                            processing, to contact You.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>For business transfers:</span>
                        <span className={styles.c4}>
                            &nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale
                            of Company assets, financing, or acquisition of all or a portion of Our business to another company.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>With Affiliates:</span>
                        <span className={styles.c4}>
                            &nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this
                            Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other
                            companies that We control or that are under common control with Us.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>With business partners:</span>
                        <span className={styles.c4}>
                            &nbsp;We may share Your information with Our business partners to offer You certain products, services or promotions.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>With other users: </span>
                        <span className={styles.c4}>
                            when You share personal information or otherwise interact in the public areas with other users, such information may be
                            viewed by all users and may be publicly distributed outside.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>With Your consent:</span>
                        <span className={styles.c4}>&nbsp;We may disclose Your personal information for any other purpose with Your consent.</span>
                    </li>
                </ul>
                <h2 className={styles.c13} id="h.848dzk7m7qa7">
                    <span className={`${styles.c9}`}>Retention of Your Personal Data</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
                        We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are
                        required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period
                        of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are
                        legally obligated to retain this data for longer time periods.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.3k707f57642x">
                    <span className={`${styles.c9}`}>Transfer of Your Personal Data</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where
                        the parties involved in the processing are located. It means that this information may be transferred to &mdash; and
                        maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the
                        data protection laws may differ than those from Your jurisdiction.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that
                        transfer.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this
                        Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate
                        controls in place including the security of Your data and other personal information.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.4xo7k1k0mzpo">
                    <span className={`${styles.c9}`}>Disclosure of Your Personal Data</span>
                </h2>
                <h3 className={styles.c15} id="h.gujpckreizka">
                    <span className={styles.c16}>Business Transactions</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide
                        notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                    </span>
                </p>
                <h3 className={styles.c15} id="h.d7bvp9o3lty7">
                    <span className={styles.c16}>Law enforcement</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in
                        response to valid requests by public authorities (e.g. a court or a government agency).
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <h3 className={styles.c15} id="h.voas3sgrnp4z">
                    <span className={styles.c16}>Other legal requirements</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_dbqzrg2bnrrq-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Comply with a legal obligation</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Protect and defend the rights or property of the Company</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Prevent or investigate possible wrongdoing in connection with the Service</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Protect the personal safety of Users of the Service or the public</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c4}>Protect against legal liability</span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <h2 className={styles.c13} id="h.f87kcjjnrq13">
                    <span className={`${styles.c9}`}>Security of Your Personal Data</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or
                        method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal
                        Data, We cannot guarantee its absolute security.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.xphhakdrd9u8">
                    <span className={`${styles.c9}`}>Detailed Information on the Processing of Your Personal Data</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and
                        transfer information about Your activity on Our Service in accordance with their Privacy Policies.
                    </span>
                </p>
                <h3 className={styles.c15} id="h.sbbxqb9t5hhp">
                    <span className={styles.c16}>Analytics</span>
                </h3>
                <p className={styles.c2}>
                    <span className={styles.c4}>We may use third-party Service providers to monitor and analyze the use of our Service.</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className="c4 c14">[LIST]</span>
                </p>
                <h3 className={styles.c15} id="h.cjv5zirtr58m">
                    <span className={styles.c16}>Email Marketing</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that
                        may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the
                        unsubscribe link or instructions provided in any email We send or by contacting Us.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c14}>[LIST]</span>
                </p>
                <h3 className={styles.c15} id="h.qp05uhjsreu3">
                    <span className={styles.c16}>Payments</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment
                        processing (e.g. payment processors).
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We will not store or collect Your payment card details. That information is provided directly to Our third-party payment
                        processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the
                        standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa,
                        Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c14}>[LIST]</span>
                </p>
                <h2 className={styles.c13} id="h.iysgpxmdwaao">
                    <span className={`${styles.c9}`}>GDPR Privacy Policy</span>
                </h2>
                <h3 className={styles.c15} id="h.t0rkme7h698q">
                    <span className={styles.c16}>Legal Basis for Processing Personal Data under GDPR</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>We may process Personal Data under the following conditions:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_eywo5t908cpf-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Consent</span>
                        <span className={styles.c4}>: You have given Your consent for processing Personal Data for one or more specific purposes.</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Performance of a contract</span>
                        <span className={styles.c4}>
                            : Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual
                            obligations thereof.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Legal obligations</span>
                        <span className={styles.c4}>
                            : Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Vital interests</span>
                        <span className={styles.c4}>
                            : Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Public interests</span>
                        <span className={styles.c4}>
                            : Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official
                            authority vested in the Company.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Legitimate interests</span>
                        <span className={styles.c4}>
                            : Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.
                        </span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in
                        particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to
                        enter into a contract.
                    </span>
                </p>
                <h3 className={styles.c15} id="h.5p6zaum2uh16">
                    <span className={styles.c16}>Your Rights under the GDPR</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>You have the right under this Privacy Policy, and by law if You are within the EU, to:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_miqi16wgybsc-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Request access to Your Personal Data</span>
                        <span className={styles.c4}>
                            . The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or
                            request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these
                            actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold
                            about You.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Request correction of the Personal Data that We hold about You</span>
                        <span className={styles.c4}>. You have the right to have any incomplete or inaccurate information We hold about You corrected.</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Object to processing of Your Personal Data</span>
                        <span className={styles.c4}>
                            . This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is
                            something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this
                            ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Request erasure of Your Personal Data</span>
                        <span className={styles.c4}>
                            . You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue
                            processing it.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Request the transfer of Your Personal Data</span>
                        <span className={styles.c4}>
                            . We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used,
                            machine-readable format. Please note that this right only applies to automated information which You initially provided
                            consent for Us to use or where We used the information to perform a contract with You.
                        </span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span className={styles.c5}>Withdraw Your consent.</span>
                        <span className={styles.c4}>
                            &nbsp;You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be
                            able to provide You with access to certain specific functionalities of the Service.
                        </span>
                    </li>
                </ul>
                <h3 className={styles.c15} id="h.wgcz9bosa0b9">
                    <span className={styles.c16}>Exercising of Your GDPR Data Protection Rights</span>
                </h3>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may
                        ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to
                        You as soon as possible.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more
                        information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.c99l3aqagbay">
                    <span className={`${styles.c9}`}>Children&#39;s Privacy</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from
                        anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal
                        Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without
                        verification of parental consent, We take steps to remove that information from Our servers.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a
                        parent, We may require Your parent&#39;s consent before We collect and use that information.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.ecxybpwpl2n2">
                    <span className={`${styles.c9}`}>Links to Other Websites</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be
                        directed to that third party&#39;s site. We strongly advise You to review the Privacy Policy of every site You visit.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites
                        or services.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.s1qgjyorhhh7">
                    <span className={`${styles.c9}`}>Changes to this Privacy Policy</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on
                        this page.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the
                        &quot;Last updated&quot; date at the top of this Privacy Policy.
                    </span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when
                        they are posted on this page.
                    </span>
                </p>
                <h2 className={styles.c13} id="h.rhij46lryv2t">
                    <span className={`${styles.c9}`}>Contact Us</span>
                </h2>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <p className={styles.c2}>
                    <span className={styles.c4}>If you have any questions about this Privacy Policy, You can contact us:</span>
                </p>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
                <ul className="c8 lst-kix_nwjcx6qwqb28-0 start">
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>By visiting this page on our website: </span>
                        <span className="c4 c14">[WEBSITE_CONTACT_PAGE_URL]</span>
                    </li>
                    <li className={`${styles.c2} ${styles.li_bullet_0} ${styles.c7} ${styles.c3}`}>
                        <span>By sending us an email: </span>
                        <span className="c4 c14">[WEBSITE_CONTACT_EMAIL]</span>
                    </li>
                </ul>
                <p className={styles.c1}>
                    <span className={styles.c4}></span>
                </p>
            </div>
        </section>
    );
}
